image: hugomods/hugo:exts

variables:
  HUGO_ENV: production

default:
  before_script:
    - apk add --no-cache go curl bash npm
    - hugo mod get -u

test:
  script:
    - hugo --minify
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  script:
    - hugo --minify
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
