image: registry.gitlab.com/pages/hugo/hugo_extended:latest

variables:
  HUGO_ENV: production
  THEME_URL: "github.com/theNewDynamic/gohugo-theme-ananke"

default:
  before_script:
    - apk add --no-cache go curl bash npm
    - hugo mod get -u $THEME_URL
    - npm install postcss postcss-cli autoprefixer

test:
  script:
    - hugo --minify
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  script:
    - hugo --minify
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
